apiVersion: v1
kind: Service
metadata:
  name: app-sevice
  namespace: eaddy-nettey
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
