apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: eaddy-nettey
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
